{% set version = "1.1-221.1" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sdmtools
  version: {{ version|replace("-", "_") }}

source:
  fn: SDMTools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/SDMTools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/SDMTools/SDMTools_{{ version }}.tar.gz
  sha256: 3825856263bdb648ca018b27dc6ab8ceaef24691215c197f8d5cd17718b54fbb
  patches:
    - b.patch

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-r.utils

  run:
    - r-base
    - r-r.utils

test:
  commands:
    - $R -e "library('SDMTools')"  # [not win]
    - "\"%R%\" -e \"library('SDMTools')\""  # [win]

about:
  home: http://www.rforge.net/SDMTools/
  license: GPL-3
  summary: This packages provides a set of tools for post processing the outcomes of species
    distribution modeling exercises. It includes novel methods for comparing models
    and tracking changes in distributions through time. It further includes methods
    for visualizing outcomes, selecting thresholds, calculating measures of accuracy
    and landscape fragmentation statistics, etc.. This package was made possible in
    part by financial support from the Australian Research Council & ARC Research Network
    for Earth System Science.
  license_family: GPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - bgruening
    - daler
    - johanneskoester
    - rvalieris
