appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: X7xgrWA0fiNevWjs4MRdALTLRcglOZNk4vG8sp+IFn/jN4L0gfYSQXKbzkYRbGNAV3lsKL8GSnSFpdnU9dyAMvU4TQaemN8MjiLpnYPw+hJyXAxqvnWJUb6M7LL+B60wIyIPS+BlKapEFJI6/EgAaR0eKZgHWNo0YEwF0uAQzSf48g6n/M1x96KDFoAcV/Hffog/ayY5TUj9w1+gzarfaxr9coBuAbd2veEle7gsZEMaIj6PME7DbRN+Lktj7fuesYoU3OJ2BA2YQEUVzaNtmCY9W/tmHul+dQCfdR1MuLZVWSTwXUNv0QSvhPc6kNk8N8dp7QfFun6yOngVdnWgjKAWurjG59MrBly8bP+Fpm6IKxu7U1Jno+l2Aw46x+ywRyrSKLKt6QwItxegkdy7hcL2gAWZSXzAX4l8Ynt8IW/0y+UTL/C3nyf7dkcgGRtH7gIyEdr1iwRTpNDSh49FhjZdv/5DIEJ5HbSi38CNLUjvZNTCKE4IOZ7/zeuH0Q44OWLLZTz92GJMNl3ySXndVgJX7EvSM2WQrvVYuYDd3LUOL+HeB/961p1ljugDBTrYDwXa6ODjxL/T8hOk1TjODg/XiUQkIymlM7KyKwUV71fq4KUfDY/zHl9SN3LNHwBmJ+NKgCArnKJF7wc/CAYOlDYOltmIoWKrgJ52KNPRKlg=
