travis:
  secure:
    BINSTAR_TOKEN: u1cRNV1wBGVUiEMIGXthPuXIdlJmzshqN6D21GPR8qTwd5X/6dzxuyHWik4U4zWH1AlD0R9GFpw8vxf0AvIoWtYTl9sDcirk7fXXNBaeFMWu0f24rgTvh737URK4Vh9SlFKwXiwcPBtguMwsNfCeNEGXhLsJLhbXwm6NUbNq2ZM828JMZqcVphr+xq24xcfC9wUktXA7RrhfjBqDNWSRBPSdzsfzq7H531UVReVdgifqEgxlomrM7VuFYOII034eGp7c/PcktkDg1g9/mRtKb6G1C5JSYzqF083Xy0qA2YLR9zrI/sg4ROGhi3DurZyYBgDI8VQCcvv07gpWY1zUaMfmNYh/FfnV+p4uaiaauFrv915xIblLfMgSYGftJkZVta6JWQiGIL49X6/5RPwhdx+bKLD/CJlW4D+/5hUmbeIfPWaA6KjmdVBpmXF5lgLuTyGB/5jbmH3HwPdgKylnYfU4SAHsJSk9YqE4Jl9utUUGSR2iL0YNVCViFJ6NkBC4VDETajHTz6shvjACzCioQuPWtvgTkfvHcMRosNEt2C8S+3hVkLiaa61z4Bs3s/28YSBpqnhzQRLPfBhn6sDYq+TVcJrZyrmaVdigex76KYbDk4eQtme6Rp2zHO8S03rivJfI9YvKUnACFjUFkhE7D4nia1aNZkBvr/+Cub8yucw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
